### ISSUE TITLE
ชื่อ package ต้องเป็นตัวอักษรเล็กเท่านั้น

### ISSUE THREAD

**Issue by up1** [DumKrerng/assignment-java-boot-camp#18]
ชื่อ package ต้องเป็นตัวอักษรเล็กเท่านั้น

**Comment by DumKrerng** [comment]
เปลี่ยน Package: User เป็น user แล้ว

**Comment by DumKrerng** [comment]
เปลี่ยน Package: Product เป็น product แล้ว

**Comment by DumKrerng** [comment]
เปลี่ยน Package: Basket เป็น basket แล้ว

**Comment by DumKrerng** [comment]
เปลี่ยน Package: Shopping เป็น shopping แล้ว

**Comment by DumKrerng** [comment]
done
